### ISSUE TITLE
Issue with <ul>

### ISSUE THREAD

**Issue by ghost** [carlosbaraza/accounts-ui-bootstrap-3-angular#3]
If i try to use 

```
<ul>
    <login-buttons></login-buttons>
    <li> another object </li>
<ul>
```

in the navbar, this will not maintain the format of the nav bar

**Comment by ghost** [comment]
Sorry, it was an unrelated problem, and was because of glyphicons. is the are way to delete this issue?

**Comment by carlosbaraza** [comment]
No worries Boney, it's fine once it's closed and solved.

Thanks for reporting it.
